name: Update README timestamp

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update README with timestamp
        run: node scripts/update-readme.js

      - name: Commit & push changes (as Anar)
        run: |
          git config user.name "Anar Iskendarov"
          git config user.email "anariskenderov@users.noreply.github.com"
          git add README.md
          git commit -m "Update README timestamp" || echo "No changes"
          git push
